### ISSUE TITLE
Soft launch `flyctl`

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#41]
We need to soft launch flyctl, which is (paradoxically) mostly doing things outside of this repo. Still, a good place for a checklist. Soft launch just means we swap out the fly.io site + docs without making any yuge announcements. The _primary_ goal for doing this is so when we start directing people to this tool, and they visit the site + login/register we don't create any nasty surprises for users

### Todos

- [x] Prep future.fly.io: rip out stuff that's incomplete, tidy up what we're keeping
- [x] Make future.fly.io live
- [x] Move JS runtime docs to js.fly.io (or similar)
- [x] Fix signup flow from CLI, it seems to dump people to the dashboard with no further instructions
- [x] Fix signup flow from homepage, we should direct people to "how to use `flyctl` after they signup

**Comment by mrkurt** [comment]
![image](https://user-images.githubusercontent.com/7724/73101886-87609080-3ea5-11ea-9886-f1f7cd730382.png)
